x-stoplight:
  docs:
    showModels: true
x-internal: true
openapi: 3.1.0
info:
  title: Events Service API Reference
  version: '1.0'
  contact:
    name: Stephen Higgins
    email: Stephen.Higgins@pamediagroup.com
  summary: Internal Events Service API for CRUD operations on CloudMatrix Events.
  description: |-
    The Events Service API exposes the functionality to create, read, update and delete CloudMatrix Events and is for
    internal use only (typically the CloudMatrix UI will utilise these endpoints to allow users to manage their events).
tags:
  - name: Event
servers:
  - url: 'https://api.event-service.streamamg.com/v1'
paths:
  '/event/{id}':
    get:
      summary: Get a single event from CloudMatrix
      description: |-
        Get a single event from CloudMatrix based on a unique identifier passed through for a tenant identified by the 
        header parameter 'tenant-id'.

        In order to fetch the event data, the user must first be authenticated (via an API-Key). This token
        should be passed during the API call through the 'x-api-key' header. 

        The API call should be made with the event 'id' as a path parameter to identify the event resource to retrieve 
        information about.
      tags:
        - Event
      operationId: get-event-data
      security:
        - ApiKey: []
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          description: Event Identifier in CloudMatrix
        - in: header
          name: tenant-id
          description: The unique identifier of the tenant
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Event data retrieved from CloudMatrix
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventData'
              examples:
                Example - Success:
                  value:
                    id: cac5a29a-42ed-4218-b695-df8c89bf7049
                    typeId: cbbba29a-42ed-4218-b695-df8c89bf7123
                    title: Football Match
                    description: Manchester United vs Fulham
                    priorityOrder: 1
                    subtitle: Premier League
                    start: '2024-02-24T15:00:00'
                    end: '2024-02-24T17:00:00'
                    offset: '2024-02-24T14:55:00'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                description: Error getting event data
                type: object
                properties:
                  status:
                    type: number
                    enum:
                      - 400
                  message:
                    type: string
                    minLength: 1
                  reason:
                    type: string
                    enum:
                      - HEADER_ERROR
                      - BAD_REQUEST_ERROR
                      - SITE_NOT_FOUND
                      - CONFIGURATION_ERROR
                      - API_KEY_ERROR
                required:
                  - status
                  - message
              examples:
                Missing Required Header:
                  value:
                    status: 400
                    message: No tenant-id supplied
                    reason: HEADER_ERROR
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                description: Invalid/Missing API Key
                type: object
                properties:
                  message:
                    type: string
                    minLength: 1
                required:
                  - message
              examples:
                Invalid API Key:
                  value:
                    message: Forbidden
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                description: No event found for id
                type: object
                properties:
                  status:
                    type: number
                    enum:
                      - 404
                  message:
                    type: string
                    minLength: 1
                  reason:
                    type: string
                    enum:
                      - NO_ENTITY_EXIST
                required:
                  - status
                  - message
              examples:
                Invalid Event Id:
                  value:
                    status: 404
                    message: No event found for id
                    reason: NO_ENTITY_EXIST
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                description: Error getting event data
                type: object
                properties:
                  status:
                    type: number
                    enum:
                      - 500
                  message:
                    type: string
                    minLength: 1
                required:
                  - status
                  - message
              examples:
                Internal Server Error:
                  value:
                    status: 500
                    message: 'Error getting event data [Error stack]'
    put:
      summary: Update an event in CloudMatrix
      description: |-
        Update an event in CloudMatrix for a tenant identified by the header parameter 'tenant-id'.

        In order to create the event data, the user must first be authenticated (via an API-Key). This token
        should be passed during the API call through the 'x-api-key' header. 

        The API call should be made with the unique event 'id' passed through in the main payload (it is not 
        automatically created by the service and database).
      tags:
        - Event
      security:
        - ApiKey: []
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          description: Event identifier in CloudMatrix of event to update
        - in: header
          name: tenant-id
          description: The unique identifier of the tenant (from CloudMatrix)
          required: true
          schema:
            type: string
            format: uuid
      operationId: update-event
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EventData'
      responses:
        '201':
          description: Updated event in CloudMatrix
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventData'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                description: Invalid request data for the event to update
                type: object
                properties:
                  statusCode:
                    type: number
                    enum:
                      - 400
                  message:
                    type: string
                    minLength: 1
                  error:
                    type: string
                    enum:
                      - Bad Request
                required:
                  - statusCode
                  - message
                  - error
              examples:
                Invalid Event Identifier:
                  value:
                    status: 400
                    message: id must be a UUID
                    error: Bad Request
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                description: Invalid/Missing API Key
                type: object
                properties:
                  message:
                    type: string
                    minLength: 1
                required:
                  - message
              examples:
                Invalid API Key:
                  value:
                    message: Forbidden
    delete:
      summary: Delete a single event from CloudMatrix
      description: |-
        Delete a single event from CloudMatrix based on a unique identifier passed through for a tenant identified by the 
        header parameter 'tenant-id'. The delete is a 'soft' delete marking the event as 'deleted' but not physically 
        removing it from the database.

        In order to fetch the event data, the user must first be authenticated (via an API-Key). This token
        should be passed during the API call through the 'x-api-key' header. 

        The API call should be made with the event 'id' as a path parameter to identify the event resource to retrieve 
        information about.
      tags:
        - Event
      operationId: delete-event-data
      security:
        - ApiKey: []
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          description: Event Identifier in CloudMatrix to mark as deleted
        - in: header
          name: tenant-id
          description: The unique identifier of the tenant
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Event data marked as deleted in CloudMatrix
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                description: Invalid/Missing API Key
                type: object
                properties:
                  message:
                    type: string
                    minLength: 1
                required:
                  - message
              examples:
                Invalid API Key:
                  value:
                    message: Forbidden
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                description: No event found for id to mark as deleted
                type: object
                properties:
                  status:
                    type: number
                    enum:
                      - 404
                  message:
                    type: string
                    minLength: 1
                  reason:
                    type: string
                    enum:
                      - NO_ENTITY_EXIST
                required:
                  - status
                  - message
              examples:
                Invalid Event Id:
                  value:
                    status: 404
                    message: No event found for id
                    reason: NO_ENTITY_EXIST
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                description: Error deleting event data
                type: object
                properties:
                  status:
                    type: number
                    enum:
                      - 500
                  message:
                    type: string
                    minLength: 1
                required:
                  - status
                  - message
              examples:
                Internal Server Error:
                  value:
                    status: 500
                    message: 'Error deleting event data [Error stack]'
    parameters:
      - schema:
          type: string
        in: header
        name: tenant-id
        description: UUID identifying tenant
        required: true
  /event:
    post:
      summary: Create a new event in CloudMatrix
      description: |
        Create a new event in CloudMatrix for a tenant identified by the header parameter 'tenant-id'.

        In order to create the event data, the user must first be authenticated (via an API-Key). This token
        should be passed during the API call through the 'x-api-key' header. 
      tags:
        - Event
      security:
        - ApiKey: []
      operationId: create-event
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateEventBody'
      responses:
        '201':
          description: Created new event in CloudMatrix
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventData'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                description: Invalid request data for the event to create
                type: object
                properties:
                  statusCode:
                    type: number
                    enum:
                      - 400
                  message:
                    type: string
                    minLength: 1
                  error:
                    type: string
                    enum:
                      - Bad Request
                required:
                  - statusCode
                  - message
                  - error
              examples:
                Invalid Event Identifier:
                  value:
                    status: 400
                    message: id must be a UUID
                    error: Bad Request
                Title Is Required:
                  value:
                    status: 400
                    message: Title must be a non-empty object
                    error: Bad Request
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                description: Invalid/Missing API Key
                type: object
                properties:
                  message:
                    type: string
                    minLength: 1
                required:
                  - message
              examples:
                Invalid API Key:
                  value:
                    message: Forbidden
        '500':
          description: Internal Server Error
    parameters:
      - schema:
          type: string
        in: header
        name: tenant-id
        description: UUID identifying tenant
        required: true
components:
  securitySchemes:
    ApiKey:
      type: apiKey
      in: header
      name: x-api-key
  schemas:
    EventData:
      type: object
      properties:
        id:
          type: string
        typeId:
          type: string
        title:
          type: string
        description:
          type: string
        priorityOrder:
          type: integer
        subtitle:
          type: string
        start:
          type: string
        end:
          type: string
        offset:
          type: string
        deleted:
          type: boolean
    CreateEventBody:
      type: object
      x-stoplight:
        id: 1u6q4wjicmuut
      title: CreateEventBody
      required:
        - typeId
        - title
        - priorityOrder
        - start
        - end
      properties:
        typeId:
          type: string
        title:
          type: string
        description:
          type: string
        priorityOrder:
          type: integer
        subtitle:
          type: string
        start:
          type: string
        end:
          type: string
        offset:
          type: number
          minimum: 0
        attributes:
          $ref: '#/components/schemas/EventAttributes'
    EventAttributes:
      type: array
      x-stoplight:
        id: 17a44d0639528
      uniqueItems: true
      minItems: 1
      description: The metadata attributes
      items:
        type: object
        properties:
          id:
            type: string
            minLength: 1
            description: CloudMatrix attribute configuration id
          value:
            type: string
            minLength: 1
            description: 'CloudMatrix attribute value (singular value like string, number etc.)'
          items:
            type: array
            uniqueItems: true
            minItems: 1
            description: CloudMatrix attribute value (collection)
            items:
              type: object
              additionalProperties: false
              properties:
                value:
                  type: string
                  minLength: 1
                  description: 'CloudMatrix attribute value (singular value like string, number etc.)'
              required:
                - value
        required:
          - id
