x-internal: true
x-stoplight:
  id: tqnb0nc0s88d2
openapi: 3.1.0
info:
  title: SNS Subscription API Reference
  version: '1.0'
  contact:
    name: ''
    email: ''
  summary: Internal SNS Subscription Service API for CloudMatrix.
  description: |-
    The SNS Subscription Service API exposes the functionality to create, read and delete CloudMatrix SNS Subscription 
    Webhooks and is for internal use only (typically the CloudMatrix UI will utilise these endpoints to allow users to manage their subscriptions).
servers:
  - url: 'https://cloudmatrix-events-api.dev.streamamg.com/api/v1/'
paths:
  '/subscription/{id}':
    delete:
      summary: Delete a single SNS Subscription from CloudMatrix
      description: |-
        This endpoint deletes an existing subscription based on its unique id. The client must provide a valid tenant-id in the request headers to identify the tenant context under which the subscription operates.
        If successful, the server responds with a 204 No Content status, indicating that the subscription was deleted without returning any content in the response body.

        Note that this is a full removal of the entry, not a soft removal.

        The user must first be authenticated (via an API-Key). This token should be passed during the API call through the 'x-api-key' header. 
      tags:
        - SNS-Subscription
      operationId: delete-sns-subscription
      security:
        - ApiKey: []
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          description: SNS Subscription in CloudMatrix to be deleted
        - in: header
          name: tenant-id
          description: The unique identifier of the tenant
          required: true
          schema:
            type: string
            format: uuid
        - in: header
          name: x-api-key
          description: The x-api-key
          required: true
          schema:
            type: string
            format: string
      responses:
        '204':
          description: SNS Subscription is deleted in CloudMatrix
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                description: Invalid/Missing API Key
                type: object
                properties:
                  message:
                    type: string
                    minLength: 1
                required:
                  - message
              examples:
                Invalid API Key:
                  value:
                    message: API Key not provided or not valid
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                description: "Subscription: {id} not found"
                type: object
                properties:
                  status:
                    type: number
                    enum:
                      - 404
                  message:
                    type: string
                    minLength: 1
                  reason:
                    type: string
                    minLength: 1
                required:
                  - statusCode
                  - message
                  - error
              examples:
                Invalid Event Id:
                  value:
                    message: "Subscription: 354a82b8-fb50-45fe-8b78-c952b06e2a82 not found"
                    error: Not Found
                    statusCode: 404
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                description: Error deleting SNS Subscription data
                type: object
                properties:
                  statusCode:
                    type: number
                    enum:
                      - 500
                  message:
                    type: string
                    minLength: 1
                required:
                  - status
                  - message
                  - error
              examples:
                Internal Server Error:
                  value:
                    message: 'Subscription deletion failed'
                    error: Internal Server Error
                    statusCode: 500
      x-stoplight:
        id: zfms911lbsgx2
    parameters:
      - schema:
          type: string
        in: header
        name: tenant-id
        description: UUID identifying tenant
        required: true
  /event:
    post:
      summary: Create a SNS Subscription in CloudMatrix
      description: |
        This endpoint creates a new subscription for a specified tenant. The client must provide a valid tenant-id in the request headers and the subscription data in the request body.
        If successful, the server responds with a 201 Created status, confirming that the subscription was successfully created.

        The user must first be authenticated (via an API-Key). This token should be passed during the API call through the 'x-api-key' header. 
      tags:
        - SNS-Subscription
      security:
        - ApiKey: []
      operationId: create-sns-subscription
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSNSSubscription'
            examples:
              SNS Subscription (article.update):
                value:
                  endpoint: 'https:www.example-sns-endpoint.com'
                  eventTypes: ['article.update']
              SNS Subscription (article.delete):
                value:
                  endpoint: 'https:www.example-sns-endpoint.com'
                  eventTypes: ['article.delete']
              SNS Subscription (article.restore):
                value:
                  endpoint: 'https:www.example-sns-endpoint.com'
                  eventTypes: ['article.restore']
              SNS Subscription (config.update):
                value:
                  endpoint: 'https:www.example-sns-endpoint.com'
                  eventTypes: ['config.update']
      responses:
        '201':
          description: Created SNS Subscription in CloudMatrix
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateSNSSubscriptionResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                description: Invalid request data for the event to create
                type: object
                properties:
                  statusCode:
                    type: number
                    enum:
                      - 400
                  message:
                    type: string
                    minLength: 1
                  error:
                    type: string
                    enum:
                      - Bad Request
                required:
                  - statusCode
                  - message
                  - error
              examples:
                Invalid Event Identifier:
                  value:
                    status: 400
                    message: id must be a UUID
                    error: Bad Request
                Title Is Required:
                  value:
                    status: 400
                    message: Title must be a non-empty object
                    error: Bad Request
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                description: Invalid/Missing API Key
                type: object
                properties:
                  message:
                    type: string
                    minLength: 1
                required:
                  - message
              examples:
                Invalid API Key:
                  value:
                    message: Forbidden
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                description: Error deleting SNS Subscription data
                type: object
                properties:
                  statusCode:
                    type: number
                    enum:
                      - 500
                  message:
                    type: string
                    minLength: 1
                required:
                  - status
                  - message
                  - error
              examples:
                Internal Server Error:
                  value:
                    message: 'Subscription deletion failed'
                    error: Internal Server Error
                    statusCode: 500
      x-stoplight:
        id: p7xw6sda7vuh1
    parameters:
      - schema:
          type: string
        in: header
        name: tenant-id
        description: UUID identifying tenant
        required: true
components:
  securitySchemes:
    ApiKey:
      type: apiKey
      in: header
      name: x-api-key
  schemas:
    CreateSNSSubscription:
      type: object
      x-stoplight:
        id: gey87qt7ekx7o
      title: CreateSNSSubscription
      required:
        - endpoint
        - eventTypes
      properties:
        endpoint:
          type: string
          minLength: 1
          description: endpoint to send the SNS message to
        eventTypes:
          type: array
          minimum: 0
          description: array of event types to subscribe to ['article.update', 'article.delete', 'article.restore', 'config.update']
    CreateSNSSubscriptionResponse:
      type: object
      x-stoplight:
        id: gey87qt7ekx7o
      title: CreateSNSSubscription
      required:
        - endpoint
        - eventTypes
      properties:
        id:
          type: string
          format: uuid
          description: unique identifier for the subscription
        tenantId:
          type: string
          minLength: 1
          description: tenant identifier
        endpoint:
          type: string
          minLength: 1
          description: endpoint to send the SNS message to
        eventTypes:
          type: array
          minimum: 0
          description: array of event types to subscribe to ['article.update', 'article.delete', 'article.restore', 'config.update']
        status:
          type: string
          minLength: 0
          description: status of the subscription
        createdAt:
          type: string
          format: string
          description: date and time the subscription was created 
  tags:
  - name: SNS-Subscription
